name: 'Release'
on:
  push:
    branches:
      - 'release'
jobs:
  release:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'
      - name: 'Use Node.js 12.0'
        uses: 'actions/setup-node@v2'
        with:
          node-version: '12.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jamashita'
      - name: 'Set up'
        run: 'yarn install --frozen-lockfile'
      - name: 'Publish to GitHub Package Registry'
        run: 'yarn release'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
